### ISSUE TITLE
Mobile Meta

### ISSUE THREAD

**Issue by Mikeysax** [cxm6467/Firehose#1]
On mobile things don't look as good as they could be.
One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.
Let me know in the comments once you figured that step out :)

**Comment by cxm6467** [comment]
I believe I added it correctly with the following code:

`<meta name="viewport" content="width=device-width, initial-scale=1">`

Let me know if this is correct and I will close the issue!  I tested it on my phone and it looks better.

**Comment by Mikeysax** [comment]
:+1:
